# Generated by Django 3.2.6 on 2021-08-17 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('counter', models.IntegerField(verbose_name='Счетчик просмотров')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_contentpage.basecontent_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AudioBaseContent',
            fields=[
                ('basecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contentpage.basecontent')),
                ('bitrate', models.IntegerField(verbose_name='битрейт')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('contentpage.basecontent',),
        ),
        migrations.CreateModel(
            name='TextBaseContent',
            fields=[
                ('basecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contentpage.basecontent')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('contentpage.basecontent',),
        ),
        migrations.CreateModel(
            name='VideoBaseContent',
            fields=[
                ('basecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contentpage.basecontent')),
                ('video_file_url', models.URLField(max_length=255, verbose_name='ссылка на видеофайл')),
                ('subtitles_url', models.URLField(max_length=255, verbose_name='ссылка на субтитры')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('contentpage.basecontent',),
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_order', models.IntegerField(verbose_name='порядок')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentpage.basecontent')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentpage.page')),
            ],
        ),
    ]
