# Generated by Django 3.2.6 on 2021-08-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
