# Generated by Django 3.2.6 on 2021-08-20 09:47

from django.db import migrations
from django.contrib.auth.models import User


def generate_superuser(apps, schema_editor):
    User.objects.create_superuser(username='admin', email='admin@test.com', password='admin')


class Migration(migrations.Migration):

    dependencies = [
        ('contentpage', '0003_auto_20210818_2231'),
    ]

    operations = [
        migrations.RunPython(generate_superuser),
    ]
